# Everything is pre-built locally so we only need to use the public path
# (only when pushing to main)
# Based on https://gitlab.com/pages/plain-html
image: busybox

pages:
  stage: deploy
  script:
    - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

